apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    qcloud-app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
  type: ClusterIP

