apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    az: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''az'']}'
    domain: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''domain'']}'
    realm: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''realm'']}'
    region: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''region'']}'
  annotations: 
    "moniker.spinnaker.io/stack": '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''domain'']}'
    "moniker.spinnaker.io/detail": prometheus    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-service-account
      containers:
      - args:
        - /bin/prometheus
          --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data --web.console.libraries=/usr/share/prometheus/console_libraries
          --web.console.templates=/usr/share/prometheus/consoles
        command:
        - /bin/sh
        - -c
        image: ccr.ccs.tencentyun.com/ccs-dev/prometheus:v2.2.1
        imagePullPolicy: Always
        name: prometheus
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config
          readOnly: true
        - mountPath: /data
          name: data-local
      nodeSelector:
        category: monitor          
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-config
        name: config
      - hostPath:
          path: /root/apollo/env/prometheus/data
        name: data-local
