apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - port: 8081
      targetPort: 9090
  type: LoadBalancer
