apiVersion: v1
data:
  prometheus-datasource.yml: |
    apiVersion: 1
    deleteDatasources:
      - name: Graphite
        orgId: 1
    datasources:
    - name: 普罗米修斯
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:8081
      version: 1
      editable: true
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: monitoring
