apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 8081
      targetPort: 3000
  type: LoadBalancer
