apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: pushgateway
      name: pushgateway
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/ccs-dev/pushgateway:v0.5.2
        name: pushgateway
        args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        volumeMounts:
        - name: host-proc
          mountPath: /host/proc
        - name: host-sys
          mountPath: /host/sys
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
        - name: host-sys
          hostPath:
            path: /sys
