apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring
  annotations: 
    "moniker.spinnaker.io/stack": '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''domain'']}'
    "moniker.spinnaker.io/detail": pushgateway  
spec:
  template:
    metadata:
      labels:
        app: pushgateway
        az: >-
          ${#stage('ApolloEnv')['context']['manifests'][0]['data']['az']}
        domain: >-
          ${#stage('ApolloEnv')['context']['manifests'][0]['data']['domain']}
        realm: >-
          ${#stage('ApolloEnv')['context']['manifests'][0]['data']['realm']}
        region: >-
          ${#stage('ApolloEnv')['context']['manifests'][0]['data']['region']}
      name: pushgateway
    spec:
      containers:
        - image: 'prom/pushgateway:v0.5.2'
          name: pushgateway
      nodeSelector:
        category: monitor
