apiVersion: v1
kind: Service
metadata:
  labels:
    app: pushgateway
    az: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''az'']}'
    domain: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''domain'']}'
    realm: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''realm'']}'
    region: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''region'']}'
  annotations: 
    "moniker.spinnaker.io/stack": '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''domain'']}'
    "moniker.spinnaker.io/detail": pushgateway
    "腾讯视频": <a href="https://v.qq.com/x/cover/e7hi6lep1yc51ca.html?vid=m0018vi92iy">琅琊榜-06</a>
  name: pushgateway-${#stage('ApolloEnv')['context']['manifests'][0]['data']['domain']}-pushgateway
  namespace: monitoring
spec:
  ports:
    - port: 8081
      targetPort: 9091
  selector:
    app: pushgateway
    az: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''az'']}'
    domain: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''domain'']}'
    realm: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''realm'']}'
    region: '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''region'']}'
  type: LoadBalancer
