apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: pushgateway
      name: pushgateway
    spec:
      containers:
      - image: prom/pushgateway:v0.5.2
        name: pushgateway
      nodeSelector:
        category: monitor   
