apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    az: ${#stage('ApolloEnv')['context']['manifests'][0]['data']['az']}
    domain: ${#stage('ApolloEnv')['context']['manifests'][0]['data']['domain']}
    realm: ${#stage('ApolloEnv')['context']['manifests'][0]['data']['realm']}
    region: ${#stage('ApolloEnv')['context']['manifests'][0]['data']['region']}   
  annotations:
    "moniker.spinnaker.io/stack": '${#stage(''ApolloEnv'')[''context''][''manifests''][0][''data''][''domain'']}'
    "moniker.spinnaker.io/detail": node-exporter   
  name: node-exporter
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/ccs-dev/node-exporter:v0.16.0
        name: node-exporter
        args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        volumeMounts:
        - name: host-proc
          mountPath: /host/proc
        - name: host-sys
          mountPath: /host/sys
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
        - name: host-sys
          hostPath:
            path: /sys
